DOT_CRUNCH_DIRECTORY = ".crunchdao"
DOT_DATA_DIRECTORY = "data"
DOT_PREDICTION_DIRECTORY = "prediction"
TOKEN_FILE = "token"
PROJECT_FILE = "project.json"
REQUIREMENTS_TXT = "requirements.txt"
REQUIREMENTS_R_TXT = "requirements.r.txt"
ENCRYPTION_JSON = "encryption.json"
DEFAULT_MODEL_DIRECTORY = "resources"
DEFAULT_MAIN_FILE_PATH = "main.py"
DEFAULT_USER_CODE_MODULE_NAME = "user_code"

MACOS_HIDDEN_FILES = [
    "__MACOSX",
    ".DS_Store",
]

IGNORED_MODEL_FILES = [
    ".git/",
    f"{DOT_CRUNCH_DIRECTORY}/",
    "__pycache__/",
    ".ipynb_checkpoints/",
    ".env",
    "*.pyc",
    *MACOS_HIDDEN_FILES,
    ENCRYPTION_JSON,
]

IGNORED_CODE_FILES = [
    *IGNORED_MODEL_FILES,
    f"/{DOT_DATA_DIRECTORY}/",
    f"/{DOT_PREDICTION_DIRECTORY}/",
]

COLAB_DETECTION_ENV_VAR = "COLAB_RELEASE_TAG"
COLAB_IGNORED_CODE_FILES = [
    "/.config/",
    "/sample_data/",
]

DEBUG_ENV_VAR = "CRUNCH_DEBUG"
API_KEY_ENV_VAR = "CRUNCH_API_KEY"
ENVIRONMENT_ENV_VAR = "CRUNCH_ENVIRONMENT"

API_BASE_URL_ENV_VAR = "CRUNCH_API_BASE_URL"
WEB_BASE_URL_ENV_VAR = "CRUNCH_WEB_BASE_URL"

API_BASE_URL_PRODUCTION = "https://api.hub.crunchdao.com/"
API_BASE_URL_STAGING = "https://api.hub.crunchdao.io/"
API_BASE_URL_DEVELOPMENT = "http://localhost:8000/"

WEB_BASE_URL_PRODUCTION = "https://hub.crunchdao.com/"
WEB_BASE_URL_STAGING = "https://hub.crunchdao.io/"
WEB_BASE_URL_DEVELOPMENT = "http://localhost:3000/"

COMPETITIONS_SOURCE_ENV_VAR = "CRUNCH_COMPETITIONS_SOURCE"

COMPETITIONS_SOURCE_LOCAL_EXAMPLE = "local:///root/crunchdao/competitions"
COMPETITIONS_SOURCE_GITHUB_DEFAULT = "github://crunchdao/competitions"
COMPETITIONS_SOURCE_CACHE_DEFAULT = "cache+https://competitions.cache.crunchdao.com"
COMPETITIONS_SOURCE_DEFAULT = COMPETITIONS_SOURCE_CACHE_DEFAULT

USER_CODE_MODULE_NAME_ENV_VAR = "USER_CODE_MODULE_NAME"
MAIN_FILE_PATH_ENV_VAR = "MAIN_FILE"

TEXT_FILE_EXTENSIONS = [
    ".txt",
    ".md",
]

RUN_VIA_CLI = False

SUBMISSION_MESSAGE_LENGTH = 1000
